# CONFIGURACOES DE BANCO DE DADOS PARA PRODUCAO (RAILWAY POSTGRES)
spring.datasource.url=${{Postgres.DATABASE_URL}}?prepareThreshold=0
spring.datasource.username=${{Postgres.PGUSER}}
spring.datasource.password=${{Postgres.PGPASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

# SERVIDOR E THYMELEAF
server.port=${PORT:8080}
spring.thymeleaf.cache=true
spring.jpa.open-in-view=false

# SEGURANCA EM PRODUCAO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false