# CONFIGURACOES DE BANCO DE DADOS PARA PRODUCAO
spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}

server.port=${PORT:8080}

spring.thymeleaf.cache=true
spring.jpa.open-in-view=false

# SEGURANCA EM PRODUCAO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false