# ? CONFIGURAÇÕES DE BANCO DE DADOS PARA PRODUÇÃO (INJETADAS PELA NUVEM)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# O servidor de produção define a porta dinamicamente
server.port=${PORT:8080}

# Cache ativo em produção para o sistema voar em performance
spring.thymeleaf.cache=true
spring.jpa.open-in-view=false

# ? SEGURANÇA MÁXIMA EM PRODUÇÃO: 'none' ou 'validate' impede o Hibernate de alterar o banco automaticamente
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Desativa logs pesados de SQL no console de produção para economizar processamento
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false