# CONTROLE DE PERFIL
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/db_abencoar
spring.datasource.username=filipe
spring.datasource.password=dusk
server.port=8080

spring.thymeleaf.cache=false
spring.jpa.open-in-view=true

# MOTOR LOCAL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# LOGS DE CONFIGURACAO
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true